### ISSUE TITLE
1.0.0-alpha7 seen as less than 0.9.1

### ISSUE THREAD

**Issue by ppetermann** [tajawal/inspector#1]
as subject sais, i have a package installed as 1.0.0-alpha7 (version constraint: "~1.0@alpha"), and inspector sais that 0.9.1 is available - which is obviously an older version.

**Comment by kamranahmedse** [comment]
Because it shows the latest stable release available and considers alpha, beta and dev releases as non-stable so in your case `1.0.0-alpha7` is being ignored.

**Comment by ppetermann** [comment]
semantic versioning: 
4. Major version zero (0.y.z) is for initial development. Anything may change at any time. The public API should not be considered stable.

**Comment by kamranahmedse** [comment]
Missed that, will fix it. Thanks for pointing out.

**Comment by kamranahmedse** [comment]
Fixed in https://github.com/tajawal/inspector/commit/f7e5f42e80aacf75230bf890e20ed41c0e709610

Did not get to verify that, but let's hope that it is ;-)
